/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acepero13_research_audio_windows_WindowsMicrophoneControl */

#ifndef _Included_com_acepero13_research_audio_windows_WindowsMicrophoneControl
#define _Included_com_acepero13_research_audio_windows_WindowsMicrophoneControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acepero13_research_audio_windows_WindowsMicrophoneControl
 * Method:    muteMicrophone
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_acepero13_research_audio_windows_WindowsMicrophoneControl_muteMicrophone
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
